dist: trusty
sudo: required
language: node_js
node_js:
  "7"

install:
  - sudo apt-get update
  - sudo apt-get install python3-dev python3-pip python3-setuptools
  - sudo -H python3 -m pip install coala-bears

script:
  - coala --ci
